import random

fruits = [
    'apple',
    'banana',
    'berry',
    'cherry',
    'chili',
    'fig',
    'grape',
    'kiwi',
    'lemon',
    'lime',
    'mango',
    'orange',
    'peach',
    'pear',
]

animals = [
    'bat',
    'bear',
    'bird',
    'camel',
    'cat',
    'cow',
    'crow',
    'deer',
    'dog',
    'dove',
    'dragon',
    'duck',
    'eagle',
    'fish',
    'fox',
    'frog',
    'goat',
    'goose',
    'hippo',
    'horse',
    'kitten',
    'lion',
    'mouse',
    'otter',
    'owl',
    'pig',
    'puppy',
    'rat',
    'seal',
    'shark',
    'sheep',
    'skunk',
    'snake',
    'spider',
    'tiger',
    'turkey',
    'viper',
    'whale',
    'wolf',
]

colors = [
    'black',
    'blue',
    'bronze',
    'brown',
    'fire',
    'forest',
    'gold',
    'gray',
    'green',
    'navy',
    'pink',
    'purple',
    'red',
    'silver',
    'sky',
    'spring',
    'steel',
    'white',
    'yellow',
]

banned = [
    'apple fish',
    'apple rat',
    'banana horse',
    'banana forest',
    'banana lion',
    'blue dragon',
    'cherry berry',
    'cherry black',
    'chili dog',
    'lemon cherry',
    'lemon frog',
    'lemon horse',
    'lemon skunk',
    'lime berry',
    'peach mango',
    'peach fish',
    'pear kitten',
    'bat rat',
    'bear cat',
    'bear dog',
    'bird dog',
    'camel apple',
    'camel berry',
    'camel bear',
    'camel frog',
    'cat orange',
    'cat bird',
    'cow apple',
    'cow bird',
    'cow dog',
    'crow berry',
    'crow bat',
    'dog pig',
    'dog gold',
    'dove red',
    'dragon berry',
    'dragon fish',
    'dragon horse',
    'dragon snake',
    'dragon wolf',
    'dragon fire',
    'duck bear',
    'duck fish',
    'eagle dog',
    'eagle red',
    'fish cat',
    'fish dog',
    'fox cat',
    'fox fire',
    'goat puppy',
    'goose berry',
    'hippo cat',
    'horse apple',
    'horse dog',
    'horse pig',
    'kitten chili',
    'kitten fish',
    'mouse dog',
    'pig fish',
    'pig lion',
    'puppy dog',
    'puppy frog',
    'rat berry',
    'rat cow',
    'rat pig',
    'rat snake',
    'shark dog',
    'sheep dog',
    'skunk cat',
    'skunk rat',
    'snake bird',
    'snake dog',
    'snake rat',
    'spider crow',
    'tiger cow',
    'tiger dragon',
    'tiger frog',
    'tiger shark',
    'turkey crow',
    'whale dog',
    'whale pig',
    'whale shark',
    'wolf berry',
    'wolf chili',
    'wolf cow',
    'wolf rat',
    'wolf spider',
    'black banana',
    'black cherry',
    'black grape',
    'black mango',
    'black peach',
    'black bird',
    'black crow',
    'black dog',
    'black fish',
    'black fox',
    'black goat',
    'black horse',
    'black lion',
    'black sheep',
    'black snake',
    'black whale',
    'black forest',
    'black gold',
    'blue berry',
    'blue cherry',
    'blue chili',
    'blue mango',
    'blue bird',
    'blue dog',
    'blue fox',
    'blue hippo',
    'blue horse',
    'blue pig',
    'blue whale',
    'blue wolf',
    'blue fire',
    'bronze dragon',
    'brown apple',
    'brown banana',
    'brown berry',
    'brown cherry',
    'brown peach',
    'brown bat',
    'brown bear',
    'brown bird',
    'brown dog',
    'brown duck',
    'brown eagle',
    'brown fish',
    'brown goat',
    'brown goose',
    'brown kitten',
    'brown mouse',
    'brown otter',
    'brown owl',
    'brown shark',
    'brown sheep',
    'brown snake',
    'brown spider',
    'brown tiger',
    'brown whale',
    'brown fire',
    'brown gold',
    'fire berry',
    'fire camel',
    'fire dragon',
    'fire goat',
    'fire snake',
    'fire tiger',
    'gold dragon',
    'gold lion',
    'gold fire',
    'gray banana',
    'gray dragon',
    'gray goose',
    'green apple',
    'green banana',
    'green cherry',
    'green grape',
    'green lemon',
    'green peach',
    'green bear',
    'green cow',
    'green dog',
    'green dragon',
    'green fox',
    'green frog',
    'green snake',
    'green forest',
    'green gold',
    'pink apple',
    'pink banana',
    'pink berry',
    'pink cherry',
    'pink grape',
    'pink lemon',
    'pink bat',
    'pink bear',
    'pink camel',
    'pink crow',
    'pink dog',
    'pink dragon',
    'pink duck',
    'pink fish',
    'pink goose',
    'pink mouse',
    'pink pig',
    'pink turkey',
    'pink whale',
    'pink gold',
    'pink steel',
    'purple apple',
    'purple banana',
    'purple berry',
    'purple cherry',
    'purple grape',
    'purple lemon',
    'purple peach',
    'purple pear',
    'purple cat',
    'purple cow',
    'purple dragon',
    'purple goose',
    'purple pig',
    'purple snake',
    'purple tiger',
    'purple turkey',
    'purple whale',
    'purple black',
    'purple fire',
    'purple forest',
    'purple sky',
    'red berry',
    'red cherry',
    'red mango',
    'red bird',
    'red dog',
    'red dragon',
    'red duck',
    'red eagle',
    'red fish',
    'red fox',
    'red goat',
    'red lion',
    'red mouse',
    'red rat',
    'red snake',
    'red tiger',
    'red turkey',
    'red whale',
    'red forest',
    'red gold',
    'silver apple',
    'silver bear',
    'silver dragon',
    'silver eagle',
    'silver fox',
    'silver otter',
    'silver wolf',
    'silver gold',
    'sky dragon',
    'sky horse',
    'sky pig',
    'spring fox',
    'white apple',
    'white berry',
    'white chili',
    'white bear',
    'white bird',
    'white crow',
    'white dragon',
    'white fox',
    'white horse',
    'white mouse',
    'white pig',
    'white rat',
    'white shark',
    'white spider',
    'white tiger',
    'white turkey',
    'white whale',
    'white wolf',
    'white fire',
    'white gold',
    'white sky',
    'yellow cherry',
    'yellow bird',
    'yellow cat',
    'yellow dog',
    'yellow dove',
    'yellow dragon',
    'yellow tiger',
    'yellow turkey',
    'yellow gold',
    'yellow spring',
]

def generate(n=2):
    """Randomly generate a simple memorable phrase.

    Args:
        n: int, number of words in the phrase, default 2, max 3.
    """
    if n not in range(1, 4):
        raise Exception("Invalid number of words for phrase: {}.".format(n))

    lists = [fruits, animals, colors]

    word_phrase = ' '.join([random.choice(l) for l in random.sample(lists, n)])

    if word_phrase in banned:
        return generate(n)
    else:
        return word_phrase
